=== GraySchofield/SavageEraNew/Assets/Resources/Config/Building.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="categoryType">
  <xs:restriction base="xs:string">
    <xs:pattern value="Item|Building|Story"/>
  </xs:restriction>
</xs:simpleType>

<xs:xs:complexType  name="requireOrProduceType">
  <xs:attribute name="class" type="xs:string" use="required"/>
  <xs:attribute name="category" type="categorytype" use="required"/>
  <xs:attribute name="type" type="xs:string" use="required"/>
  <xs:element name="Count" type="xs:negativeInteger" minOccurs="0" maxOccurs="1"/>
</xs:simpleType>

<xs:complexType name="buildingType">
	<xs:attribute name="type" type="xs:string" use="required"/>
	<xs:element name="Occupation" type="xs:string" minOccurs="0" maxOccurs="1"/>
	<xs:element name="Capacity" type="xs:negativeInteger" minOccurs="0" maxOccurs="1"/>
	<xs:element name="Produce" type="requireOrProduceType" minOccurs="0" maxOccurs="unbounded"/>
	<xs:element name="Require" type="requireOrProduceType" minOccurs="0" maxOccurs="unbounded"/>
</xs:complexType>

<xs:element name="Buildings"/>
	<xs:complexType>
		<xs:element name="Building" type="buildingType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:complexType>
</xs:element>		

</xs:schema>

=== GraySchofield/SavageEraNew/Assets/Resources/Config/Building.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Buildings
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Building.xsd">

<Building type="wooden_house" class="House">
	<Capacity>5</Capacity>
</Building>

<Building type="science_lvl_1" class="AcademicConstruction"/>

<Building type="weather_instrument" class="AcademicConstruction"/>

<Building type="science_lvl_2" class="AcademicConstruction"/>

<Building type="grass_land" class="ProductionConstruction">
	<Occupation>grass_land_worker</Occupation>
	<Produce class="Resource" category="Item" type="hay">
		<Count>50</Count>
	</Produce>
	<Require class="Resource" category="Item" type="branch">
		<Count>10</Count>
	</Require>
</Building>

<Building type="stone_mine" class="ProductionConstruction">
	<Occupation>stone_miner</Occupation>
	<Produce class="Resource" category="Item" type="flint">
		<Count>40</Count>
	</Produce>
	<Require class="Resource" category="Item" type="hay">
		<Count>10</Count>
	</Require>
</Building>

<Building type="basic_farm" class="ProductionConstruction">
	<Occupation>farmer</Occupation>
	
	<Produce class="Food" category="Item" type="carrot">
		<Count>10</Count>
	</Produce>
	<Produce class="Food" category="Item" type="potato">
		<Count>2</Count>
	</Produce>
	<Require class="Resource" category="Item" type="hay">
		<Count>15</Count>
	</Require>
	<Require class="Resource" category="Item" type="flint">
		<Count>20</Count>
	</Require>
</Building>

<Building type="basic_pasture" class="ProductionConstruction">	
	<Occupation>herder</Occupation>	
	
	<Produce class="Food" category="Item" type="lamp">
		<Count>5</Count>
	</Produce>
	<Produce class="Resource" category="Item" type="wool">
		<Count>5</Count>
	</Produce>
	<Require class="Resource" category="Item" type="flint">
		<Count>5</Count>
	</Require>
	<Require class="Food" category="Item" type="carrot">
		<Count>9</Count>
	</Require>
</Building>

<Building type="iron_cook_pot" class="TechnologyConstruction"/>	

<Building type="black_smith" class="TechnologyConstruction"/>	


<Building type="advanced_farm" class="ProductionConstruction">
	<Occupation>farmer</Occupation>
	<Produce class="Food" category="Item" type="carrot">
		<Count>10</Count>
	</Produce>
	<Produce class="Food" category="Item" type="potato">
		<Count>2</Count>
	</Produce>
	<Produce class="Food" category="Item" type="tomato">
		<Count>1</Count>
	</Produce>
	<Produce class="Food" category="Item" type="chili">
		<Count>1</Count>
	</Produce>
	<Require class="Resource" category="Item" type="hay">
		<Count>15</Count>
	</Require>
	<Require class="Resource" category="Item" type="flint">
		<Count>20</Count>
	</Require>
</Building>


<Building type="advanced_pasture" class="ProductionConstruction">	
	<Occupation>herder</Occupation>	
	
	<Produce class="Food" category="Item" type="lamp">
		<Count>3</Count>
	</Produce>
	
	<Produce class="Resource" category="Item" type="wool">
		<Count>5</Count>
	</Produce>
	
	<Produce class="Food" category="Item" type="beef">
		<Count>1</Count>
	</Produce>
	
	<Produce class="Food" category="Item" type="milk">
		<Count>1</Count>
	</Produce>
	
	<Require class="Resource" category="Item" type="flint">
		<Count>5</Count>
	</Require>
	<Require class="Food" category="Item" type="carrot">
		<Count>9</Count>
	</Require>
</Building>

<Building type="gear_shop" class="TechnologyConstruction"/>	

<Building type="research_facility" class="TechnologyConstruction"/>	

<Building type="element_hall" class="TechnologyConstruction"/>


<Building type="evil_chamber" class="TechnologyConstruction"/>
  

</Buildings>
