=== GraySchofield/SavageEraNew/Assets/Resources/Config/Story.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:xs:complexType  name="consequenceType">
  <xs:attribute name="type" type="xs:string" use="required"/>
  <xs:element name="Weight" type="xs:decimal" minOccurs="0" maxOccurs="1"/>
</xs:simpleType>

<xs:complexType name="optionType">
	<xs:attribute name="type" type="xs:string" use="required"/>
	<xs:element name="Consequence" type="consequenceType" minOccurs="0" maxOccurs="unbounded"/>
</xs:complexType>

<xs:complexType name="storyType">
	<xs:attribute name="type" type="xs:string" use="required"/>
	<xs:element name="Option" type="optionType" minOccurs="0" maxOccurs="unbounded"/>
</xs:complexType>

<xs:element name="Stories"/>
	<xs:complexType>
		<xs:element name="Story" type="storyType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:complexType>
</xs:element>		

</xs:schema>

=== GraySchofield/SavageEraNew/Assets/Resources/Config/Story.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Stories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Story.xsd">

	<Story type="story_rain">
	</Story>
	<Story type="story_snow">
	</Story>
	<Story type="story_sunny">
	</Story>
	<Story type="story_fog">
	</Story>
	<Story type="story_spring">
	</Story>
  <Story type="story_spring_hint_monsters">
	</Story>
  <Story type="story_summer">
	</Story>
	<Story type="story_autumn">
	</Story>
	<Story type="story_winter">
	</Story>
  
  <Story type="story_hint_pick_resource">
  </Story>
  
  <Story type="story_hint_make_tool">
  </Story>
  
  <Story type="story_hint_storage">
  </Story>
  
  <Story type="story_hint_use_tool">
  </Story>
  

  <Story type="story_hint_tool">
	</Story>
	<Story type="story_hint_tool_change">
	</Story>
	<Story type="story_hint_house">
	</Story>
	<Story type="story_hint_umbrella">
	</Story>
	<Story type="story_hint_hungary">
	</Story>
	<Story type="story_hint_trap">
	</Story>
	<Story type="story_hint_battle">
	</Story>
	<Story type="story_hint_cook">
	</Story>
	<Story type="story_hint_darknees">
	</Story>
  <Story type="story_hint_welcome">
  </Story>
  <Story type="story_hint_death">
  </Story>
  <Story type="story_hint_night_bad_for_adventure">
  </Story>
	
	<Story type="story_hint_night_summer_two">
	</Story>



  <Story type="story_spring_mouse_eaten">
    <Option type="option_dummy">
      <Consequence type="cons_loose_random_food" />
    </Option>
  </Story>

  <Story type="story_boss_day_20">
    <NeedPop>true</NeedPop>
		<Option type="option_fight">
			<Consequence type="cons_fight_boss_20" />
		</Option>
	</Story>
  
  
  <Story type="story_boss_20_hint">
    <NeedPop>true</NeedPop>
		<Option type="option_confirm">
		</Option>
	</Story>
  
   <Story type="story_boss_35_hint">
    <NeedPop>true</NeedPop>
		<Option type="option_confirm">
		</Option>
	</Story>
    
  
 <Story type="story_boss_50_hint">
    <NeedPop>true</NeedPop>
		<Option type="option_confirm">
		</Option>
	</Story>
    
	
	
	<Story type="story_boss_day_35">
    <NeedPop>true</NeedPop>
    <Option type="option_fight">
			<Consequence type="cons_fight_boss_35" />
		</Option>
	</Story>
	
	<Story type="story_boss_day_50">
    <NeedPop>true</NeedPop>
    <Option type="option_fight">
			<Consequence type="cons_fight_boss_50" />
		</Option>
	</Story>
	
	
	<Story type="story_boss_day_65">
    <NeedPop>true</NeedPop>
    <Option type="option_fight">
			<Consequence type="cons_fight_boss_65" />
		</Option>
	</Story>
	
	
	<Story type="story_hint_night">
		<Option type="option_dummy">
			<Consequence type="cons_hint_night" />
		</Option>
	</Story>
	<Story type="story_hint_sunny">
		<Option type="option_dummy">
			<Consequence type="cons_hint_sunny" />
		</Option>
	</Story>
	<Story type="story_hint_rain">
		<Option type="option_dummy">
			<Consequence type="cons_hint_rain" />
		</Option>
	</Story>
	
	<Story type="story_hint_snow">
		<Option type="option_dummy">
			<Consequence type="cons_hint_snow" />
		</Option>
	</Story>
	
	<Story type="story_hint_fog">
		<Option type="option_dummy">
			<Consequence type="cons_hint_fog" />
		</Option>
	</Story>
	
	<Story type="story_hint_special_resource">
	</Story>
	<Story type="story_hint_winter_comming">
	</Story>
	<Story type="story_hint_cook_two">
	</Story>
  
  <Story type="story_hint_soul">
  </Story>
	<Story type="story_hint_world_story_1">
  </Story>
  <Story type="story_hint_world_story_2">
  </Story>
  <Story type="story_hint_world_story_3">
  </Story>
  <Story type="story_hint_world_story_4">
  </Story>
  <Story type="story_hint_world_story_5">
  </Story>
  <Story type="story_hint_world_story_6">
  </Story>
  <Story type="story_hint_world_story_7">
  </Story>
  <Story type="story_hint_world_story_8">
  </Story>
  <Story type="story_hint_world_story_9">
  </Story>
  
  <Story type="story_go_to_shop">
    <NeedPop>true</NeedPop>
    <Option type="option_confirm">
    </Option>
  </Story>
	
	<Story type="story_heatstroke">
		<Option type="option_dummy">
			<Consequence type="cons_heatstroke" />
		</Option>
	</Story>
	<Story type="story_dizzy">
		<Option type="option_dummy">
			<Consequence type="cons_dizzy" />
		</Option>
	</Story>
	<Story type="story_frozen">
		<Option type="option_dummy">
			<Consequence type="cons_frozen" />
		</Option>
	</Story>
	
	<Story type="story_crow_attack">
		<Option type="option_dummy">
			<Consequence type="cons_harvest_stop"/>
		</Option>
	</Story>
	
	<Story type="story_mouse_attack_one">
		<Option type="option_dummy">
			<Configs>
				<Exclusive>true</Exclusive>
				<Weighted>true</Weighted>
			</Configs>
			<Consequence type="cons_lose_carrot_10">
				<Configs>
					<Probability>0.2</Probability>
				</Configs>
			</Consequence>
			<Consequence type="cons_lose_potato_5">
				<Configs>
					<Probability>0.2</Probability>
				</Configs>
			</Consequence>
			<Consequence type="cons_lose_potato_10">
				<Configs>
					<Probability>0.2</Probability>
				</Configs>
			</Consequence>
			<Consequence type="cons_lose_carrot_20">
				<Configs>
					<Probability>0.2</Probability>
				</Configs>
			</Consequence>
			<Consequence type="cons_lose_tomato_10">
				<Configs>
					<Probability>0.2</Probability>
				</Configs>
			</Consequence>
		</Option>
	</Story>
	
	

  
<Story type="story_weather_too_humid_loose_resource">
  <Option type="option_dummy">
    <Consequence type="cons_loose_random_resource_from_wet" />
  </Option>
</Story>


  <Story type="story_weather_too_hot_loose_food">
    <Option type="option_dummy">
      <Consequence type="cons_loose_random_food_from_heat"/>
    </Option>
  </Story>

  



  <Story type="story_hot_lose_lamp">
		<Option type="option_dummy">
			<Consequence type="cons_lose_lamp_10" />
		</Option>
	</Story>
	
	
	<Story type="story_villagers_frozen">
		<Option type="option_dummy">
			<Consequence type="cons_pop_down_5" />
		</Option>
	</Story>	
	
	<Story type="story_villagers_heatstroke">
		<Option type="option_dummy">
			<Consequence type="cons_pop_down_3" />
		</Option>
	</Story>
	
	<Story type="story_villagers_stonemine_accident">
		<Option type="option_dummy">
			<Consequence type="cons_pop_down_2" />
		</Option>
	</Story>
	
	<Story type="story_elf_dry">
		<Option type="option_dummy">
			<Consequence type="cons_pop_down_2" />
		</Option>
	</Story>
	

	<Story type="story_too_dry_to_work">
		<Option type="option_dummy">
			<Consequence type="cons_harvest_stop" />
		</Option>
	</Story>
	
	<Story type="story_wooden_house_rain_broken">
		<Option type="option_dummy">
			<Consequence type="cons_wooden_house_broken" />
		</Option>
	</Story>
	
	<Story type="story_wooden_house_burn">
		<Option type="option_dummy">
			<Consequence type="cons_wooden_house_broken_3" />
		</Option>
	</Story>

	
	<Story type="story_people_enter_one">
		<Option type="option_dummy">
			<Consequence type="cons_pop_up_1" />
		</Option>
	</Story>
	
	<Story type="story_people_enter_two">
		<Option type="option_dummy">
			<Consequence type="cons_pop_up_2" />
		</Option>
	</Story>
	
	<Story type="story_people_enter_three">
		<Option type="option_dummy">
			<Consequence type="cons_pop_up_3" />
		</Option>
	</Story>
	
	<Story type="story_people_enter_five">
		<Option type="option_dummy">
			<Consequence type="cons_pop_up_5">
			</Consequence>
		</Option>
	</Story>
	
	
	<Story type="story_new_elf_one_by_totem">
		<Option type="option_dummy">
			<Consequence type="cons_pop_up_1">
			</Consequence>
		</Option>
	</Story>
	
	
	
	<Story type="story_find_map_dust_land">
		<Option type="option_dummy">
			<Consequence type="cons_get_map_dust_land" />
		</Option>
	</Story>


  <Story type ="story_evil_totem_attracks_monster">
    <Option type="option_dummy">
      <Consequence type="cons_evil_totem" />
    </Option>
  </Story>

  
  <Story type ="story_stuff_stolen">
    <Option type="option_dummy">
      <Consequence type="cons_loose_random_resource" />
    </Option>
  </Story>


  <Story type ="story_night_attracks_monster">
    <Option type="option_dummy">
      <Consequence type="cons_evil_totem" />
    </Option>
  </Story>


  <Story type="story_lucky_one">
		<Option type="option_dummy">
			<Configs>
				<Exclusive>true</Exclusive>
				<Weighted>true</Weighted>
			</Configs>
			<Consequence type="cons_gain_random_food">
				<Configs>
					<Probability>0.33</Probability>
				</Configs>
			</Consequence>	
			<Consequence type="cons_gain_random_normal_resource">
				<Configs>
					<Probability>0.33</Probability>
				</Configs>
			</Consequence>
			<Consequence type="cons_gain_random_tool">
				<Configs>
					<Probability>0.34</Probability>
				</Configs>
			</Consequence>
					
		</Option>
	</Story>
	

	<Story type="story_lucky_two">
		<Option type="option_dummy">
			<Configs>
				<Exclusive>true</Exclusive>
				<Weighted>true</Weighted>
			</Configs>
			<Consequence type="cons_gain_random_food">
				<Configs>
					<Probability>0.25</Probability>
				</Configs>
			</Consequence>	
			<Consequence type="cons_gain_random_normal_resource">
				<Configs>
					<Probability>0.25</Probability>
				</Configs>
			</Consequence>
			<Consequence type="cons_gain_random_rare_resource">
				<Configs>
					<Probability>0.25</Probability>
				</Configs>
			</Consequence>
			<Consequence type="cons_gain_random_tool">
				<Configs>
					<Probability>0.25</Probability>
				</Configs>
			</Consequence>
					
		</Option>
	</Story>
	
	<Story type="story_unlucky_one">
		<Option type="option_dummy">
			<Configs>
				<Exclusive>true</Exclusive>
				<Weighted>true</Weighted>
			</Configs>
			<Consequence type="cons_loose_random_food">
				<Configs>
					<Probability>0.5</Probability>
				</Configs>
			</Consequence>	
			<Consequence type="cons_loose_random_resource">
				<Configs>
					<Probability>0.5</Probability>
				</Configs>
			</Consequence>		
		</Option>
	</Story>


  
<Story type="story_viper_attack_elf">
  <Option type="option_yes">
    <Consequence type="cons_goodness_up">
    </Consequence>
